# Generated by Django 5.2.5 on 2025-09-05 10:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_returned',
            new_name='returned',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'book', 'returned')},
        ),
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 10, 41, 57, 527025, tzinfo=datetime.timezone.utc)),
        ),
    ]